export { default as Home } from "./Home"
export { default as Landing } from "./Landing"
export { default as About } from "./About"
export { default as Team } from "./Team"
export { default as Gallery } from "./Gallery"
export { default as Contact } from "./Contact"